global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node-1"
    scrape_interval: 5s
    static_configs:
      - targets:
          - "18.232.154.216:9100"
  - job_name: "node-2"
    scrape_interval: 5s
    static_configs:
      - targets:
          - "54.235.24.88:9100"

  - job_name: "node-3"
    scrape_interval: 5s
    static_configs:
      - targets:
          - "98.85.253.20:9100"

  - job_name: "all"
    scrape_interval: 5s
    static_configs:
      - targets:
          - "18.232.154.216:9100"
          - "54.235.24.88:9100"
          - "98.85.253.20:9100"
