- name: Command vs Shell
  hosts: nodes
  become: yes
  gather_facts: yes
  vars:
    host_os: "{{ ansible_facts['os_family'] }}"
    user: "{{ ansible_user_id }}"

  tasks:
    - name: Install nginx
      shell: apt update && apt install nginx -y

      when: host_os == 'Debian'

    - name: Install nginx
      shell: yum update && yum install nginx -y

      when: host_os == 'RedHat'

    - name: Copy index file
      template:
        src: index.j2
        dest: /var/www/html/index.html

      when: host_os == 'Debian'

    - name: Copy index to Centos
      template:
        src: index.j2
        dest: /usr/share/nginx/html/index.html
      when: host_os == 'RedHat'
