- name: Install Packages
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Install nginx in Centos
      dnf:
        name: nginx
        state: present
      # when: ansible_user == "ec2-user"
      when: ansible_facts['os_family'] == "Redhat"

    - name: Install nginx in Ubuntu
      apt:
        name: nginx
        state: present
      # when: ansible_user == "ubuntu"
      when: ansible_facts['os_family'] == "Debian"
