name: Terraform apply
on:
  push:
    branches:
      - git-actions
  pull_request:
    branches:
      - git-actions

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: Git

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v7

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform apply
        run: terraform apply -auto-approve
